/**
 * Copyright (C) 2026 StoneDogCode L.L.C.
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import js from "@eslint/js";
import globals from "globals";
import tsPlugin from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";

/**
 * Flat config, migrated from `.eslintrc.cjs`.
 *
 * eslint 9 deprecated eslintrc and eslint 10 removes it, so this had to happen
 * either way. Nothing here depends on `eslint-plugin-react`, which is what
 * pins several sibling repos to eslint 9, so this one goes to 10.
 *
 * Three translations are not one-to-one:
 *
 *   - `env: { node, es2022 }` has no flat equivalent; the `globals` package
 *     carries the same set. `jest` stays scoped to the test files, as the old
 *     `overrides` block had it, so a `describe` cannot appear in shipped code.
 *   - `ignorePatterns` entries gain `**`. Flat config matches them against the
 *     path from this file's directory, so a bare `dist/` would only ignore the
 *     root one -- wrong in a workspaces repo with a `dist/` per package.
 *   - The lint script loses `--ext ts,tsx`, a flag flat config dropped. That
 *     widens the file set to the `.mjs` tooling in `scripts/`, which had never
 *     been linted; it gets its own Node block below.
 */
export default [
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "**/coverage/**",
      "**/generated.ts",
      // Generated by their own tools and not ours to lint. next-env.d.ts in
      // particular is REGENERATED on every build, so any fix to it is undone.
      "**/.next/**",
      "**/next-env.d.ts",
      "**/styled-system/**",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: { ecmaVersion: 2022, sourceType: "module" },
      globals: { ...globals.node },
    },
    plugins: { "@typescript-eslint": tsPlugin },
    rules: {
      // typescript-eslint's own list of the core rules the compiler enforces
      // better. `no-undef` and `no-redeclare` are wrong rather than noisy on
      // TypeScript: one cannot see a type-only reference, the other reads
      // overload signatures as duplicates.
      ...tsPlugin.configs["flat/eslint-recommended"].rules,
      ...tsPlugin.configs.recommended.rules,
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    files: ["**/*.mjs"],
    languageOptions: { sourceType: "module", globals: { ...globals.node } },
    rules: {
      // Same underscore convention as the TypeScript block above. Without it
      // `const { $schema: _schema, ...rule } = raw` -- a deliberate discard --
      // reads as a defect.
      "no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    files: ["**/test/**/*.ts"],
    languageOptions: { globals: { ...globals.jest } },
    rules: {
      // The schema-parity test compares runtime values on purpose; a static
      // import would make a mismatch a type error rather than a value diff.
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  },
];
