/**
 * Copyright (C) 2026 StoneDogCode L.L.C.
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * The packages ship as ESM with NodeNext resolution, so their intra-package
 * imports carry `.js` extensions that point at TypeScript sources during a test
 * run. `moduleNameMapper` strips them; without it every import fails with
 * "Cannot find module './facts.js'".
 *
 * Tests themselves compile to CommonJS (see tsconfig.test.json) — that is a
 * test-harness choice and does not affect what the packages emit.
 */
export default {
  preset: "ts-jest",
  testEnvironment: "node",
  roots: ["<rootDir>/packages", "<rootDir>/apps"],
  /**
   * Next's `standalone` output traces a COPY of every workspace package into
   * .next/. Jest's module map then finds two packages claiming the name
   * `@optima-compliance/engine` and refuses to resolve either — a failure that reads as a
   * broken import and is actually a stale build artifact.
   */
  modulePathIgnorePatterns: ["<rootDir>/apps/web/.next/", "<rootDir>/apps/web/styled-system/"],
  testMatch: ["**/test/**/*.test.ts"],
  moduleNameMapper: {
    // Workspace packages resolve to SOURCE, not to dist. An app's tests must
    // not depend on a build step having run first, or a clean checkout fails
    // its own suite in a way that looks like a code error.
    "^@optima-compliance/engine$": "<rootDir>/packages/engine/src/index.ts",
    "^@optima-compliance/rules$": "<rootDir>/packages/rules/src/index.ts",
    "^@optima-compliance/db$": "<rootDir>/packages/db/src/index.ts",
    "^server-only$": "<rootDir>/test-support/server-only.cjs",
    // The web app's own `@/` alias, mirroring `apps/web/tsconfig.json`. Without
    // it a test cannot import a route or a page at all — anything reaching
    // `@/lib/server` fails to resolve — so route-level coverage was
    // structurally impossible rather than merely absent (NEH-1147).
    "^@/(.*)$": "<rootDir>/apps/web/src/$1",
    "^@optima-compliance/reminders$": "<rootDir>/packages/reminders/src/index.ts",
    "^@optima-compliance/export$": "<rootDir>/packages/export/src/index.ts",
    // @stonedogcode/style is INSTALLED FROM npm (NEH-1004) and ships TypeScript
    // source rather than a bundle, so both entry points map to that source. The
    // mapper is still needed after the move off the submodule: ts-jest has no
    // "exports" resolver, so `@stonedogcode/style/preset` — a subpath that
    // exists only in the package's `exports` map — does not resolve on its own.
    // Its `preset` entry runs in Node at build time and is what the
    // theme-completeness test reads.
    "^@stonedogcode/style/preset$":
      "<rootDir>/node_modules/@stonedogcode/style/src/preset/index.ts",
    "^@stonedogcode/style$": "<rootDir>/node_modules/@stonedogcode/style/src/index.ts",
    "^(\\.{1,2}/.*)\\.js$": "$1",
  },
  transform: {
    "^.+\\.tsx?$": ["ts-jest", { tsconfig: "<rootDir>/tsconfig.test.json" }],
  },
  /**
   * `@stonedogcode/style` is the one dependency that must be TRANSFORMED rather
   * than required as-is, and it is the direct consequence of installing it from
   * the registry (NEH-1004).
   *
   * The package ships TypeScript SOURCE, not a bundle — Panda extracts styles
   * by parsing source at the consumer's build, so a compiled `dist` would emit
   * class names nobody generated CSS for. While it was a workspace submodule
   * its files lived under `packages/`, outside jest's default
   * `transformIgnorePatterns`, and ts-jest compiled them like any other source.
   * Moving it into `node_modules` put it behind that default, and the failure
   * names neither the package nor the move:
   *
   *     SyntaxError: Cannot use import statement outside a module
   *
   * which reads as an ESM/CJS misconfiguration in the test harness.
   */
  transformIgnorePatterns: ["/node_modules/(?!@stonedogcode/style/)"],

  /*
    EVERY source file, not only the ones a test happens to import.

    This is the coverage metric's own version of the failure this repo keeps
    finding elsewhere: a green result over an empty set. Jest's default is to
    instrument only files that a test loads, so a file nothing imports is not
    counted as uncovered — it is not counted at all, and the percentage is
    computed over a denominator that shrinks as coverage gets worse.

    Measured 2026-08-29, the same 698 tests report:

        default (files touched by tests)   94.25% of   923 statements
        every source file                  62.00% of 1374 statements

    Same suite, same day. 451 statements — a third of the codebase — were
    invisible to the number, and the number that hid them was the flattering
    one. `collectCoverageFrom` is what makes the denominator the codebase
    rather than the test suite's reach.

    `generated.ts` is excluded because it is the rule barrel, regenerated by
    `rules:barrel` and already guarded by `rules:barrel:check`.
  */
  /*
    `text-summary` for a person, `json-summary` for the gate, and nothing else.
    The default set includes `lcov` and `clover`, which write a few thousand
    files nobody reads on the way to a number the gate needs one line of.
  */
  coverageReporters: ["text-summary", "json-summary"],

  collectCoverageFrom: [
    "packages/*/src/**/*.ts",
    "apps/*/src/**/*.{ts,tsx}",
    "!**/*.d.ts",
    "!packages/rules/src/generated.ts",
  ],

  /*
    A FLOOR, not a target, and set two points under today's measurement so an
    ordinary refactor cannot redden `main` — deleting dead code moves these
    numbers without anything being less tested.

    Global only. Per-directory thresholds penalise moving a file and turn into
    a maintenance surface of their own; the global floor stops the bleeding and
    ratchets up as the gaps close.

        measured 2026-08-29    62.00 / 55.04 / 58.76 / 60.38
        floor                  60    / 53    / 56    / 58

    Raise these when real coverage lands. Never lower them to make a branch
    green — that is the ratchet running backwards, and it is how a floor
    becomes a formality.
  */
  coverageThreshold: {
    global: {
      statements: 60,
      branches: 53,
      functions: 56,
      lines: 58,
    },
  },
};
